// <auto-generated />
using System;
using DenemeForeignKey.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DenemeForeignKey.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240103001310_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DenemeForeignKey.Entities.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GymName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("DenemeForeignKey.Entities.SpecialCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("SpecialCourseId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialCourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SpecialCourseId");

                    b.ToTable("SpecialCourses");
                });

            modelBuilder.Entity("DenemeForeignKey.Entities.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialCourseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialCourseId");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("DenemeForeignKey.Entities.SpecialCourse", b =>
                {
                    b.HasOne("DenemeForeignKey.Entities.SpecialCourse", null)
                        .WithMany("SpecialCourses")
                        .HasForeignKey("SpecialCourseId");
                });

            modelBuilder.Entity("DenemeForeignKey.Entities.Trainer", b =>
                {
                    b.HasOne("DenemeForeignKey.Entities.SpecialCourse", "SpecialCourse")
                        .WithMany()
                        .HasForeignKey("SpecialCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecialCourse");
                });

            modelBuilder.Entity("DenemeForeignKey.Entities.SpecialCourse", b =>
                {
                    b.Navigation("SpecialCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
